version: "3"
services:
  redis:
    image: redis:4.0.14-alpine
    ports:
      - 6379:6379
    networks:
      demo:
        aliases:
          - redis.demo.docker
          - redis

  s3:
    image: minio/minio:RELEASE.2022-02-01T18-00-14Z
    ports:
      - 9000:9000
    networks:
      demo:
        aliases:
          - s3.demo.docker
          - s3
    environment:
      MINIO_ROOT_USER: "not-a-real-id"
      MINIO_ROOT_PASSWORD: "not-a-real-key"
      MINIO_KMS_SECRET_KEY: "minio:/KOfihJwYHRz25Q1VCSPxYVBP8lC+YvhURlxajF3TYk="
    command: server /data

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    depends_on:
      - redis
      - s3
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      demo:
    command: yarn run server:dev

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
      - s3
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      demo:
    command: ./worker.sh

  frontend:
    build: ./frontend
    depends_on:
      - server
      - worker
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    networks:
      demo:

networks:
  demo:
    driver: bridge
